Update 3rdPartyInstallsWaiteing?

diff --git a/3rdPartyInstallsWaiteing? b/3rdPartyInstallsWaiteing?
--- a/3rdPartyInstallsWaiteing?
+++ b/3rdPartyInstallsWaiteing?
@@ -1,16 +1,55 @@
 #----------AUTHOR------------
 	# Will Pierce
 	# 140801
-	## must use WaitingRoom-List Extension Attribute for this to work
-## is there a waiting room text file?
-if [ /Users/Shared/waitingRoom.txt ];then
-## YES
-### Display waitingRoom.txt SET to failure
-cat /Users/Shared/waitingRoom.txt
-exit 2
 
-## NO
+#----------
+## must use WaitingRoom-List Extension Attribute for this to work
+## https://github.com/quedayone/ExtensionAttributes/blob/master/WaitingRoom-List
+
+#----------VARIABLES---------
+	# Thanks to 
+	# Jacob Salmela
+	# https://bitbucket.org/jacob_salmela/geeklets
+	# For color codes
+
+	# These variables are to give the text color, which makes the scripts more useful
+	# At a glance, you can tell if the system is in good shape (green), has a minor problem (yellow), or needs immediate attention (red)
+	# The end variable is required to show where the coloring should end
+	# An example would be if you only wanted one word to be color, that word would need to end with the $end variable
+	# See more colors and options here:
+	# http://www.csc.uvic.ca/~sae/seng265/fall04/tips/s265s047-tips/bash-using-colors.html
+	#
+	# If the colors are not working, try changing any echo commands to printf. 
+	# If you make this change, you will also need to add a \n to the end of the commands so it goes to a newline
+	# If you want to use echo, make sure the #!/bin/bash is not the first line and then echos will print the colors just fine
+	end="\x1b[0m"
+	
+	bold="\x1b[001m"
+	underscore="\x1b[004m"
+	blink="\x1b[005m"
+	
+	red="\x1b[031m"
+	green="\x1b[032m"
+	yellow="\x1b[033m"
+	blue="\x1b[034m"
+	magenta="\x1b[035m"
+	cyan="\x1b[036m"
+	white="\x1b[037m"
+#----------
+
+## is there a waiting room text file?
+if [ d- /Users/Shared/waitingRoom.txt ];then
+## YES there is a waiting room text file
+
+### Display waitingRoom.txt & SET status feedback image to failure
+echo "${red}Waiting room:${end}"
+echo ${yellow}`cat /Users/Shared/waitingRoom.txt`${end}
+exit 1
+
 else
-echo "No installs waiting"
+## NO there NOT a waiting room text file
+echo "Waiting room:"
+echo "${green}No installs waiting"${end}
 ### Set to success
 exit 0
+fi
